version: '3'
services:
  api:
    build: ./backend/
    #command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    ports:
      - 3001:3000
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db
      FRONTEND_DOMAIN: "http://localhost:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
      
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
  front:
    build: ./frontend/
    volumes:
      # - ./frontend/app:/front
      - ./frontend:/front
    ports:
      # - 3000:3000
      - 3000:80
    environment:
      REACT_APP_API_HOST: http://localhost:3001
      CHOKIDAR_USEPOLLING: true
    tty: true
    stdin_open: true
    depends_on:
      - api

volumes:
  db-volume: