version: '3'
services:
  api:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - 3001:3001
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
  front:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/front
    command: sh -c "yarn start"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    depends_on:
      - api
  web:
    build:
      context: ./nginx
    volumes:
      - public-data:/web/public
      - tmp-data:/web/tmp
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  public-data:
  tmp-data:
  log-data:
  db-volume: